import express from "express";
import { createRoom, getRoom, leaveRoom } from "../Controllers/room.controller.js";
import { authMiddleware } from "../middlewares/auth.middleware.js";
import { validateRequestBody } from "../middlewares/validation.middleware.js";

const roomRoute = express.Router();

// Create room doesn't need roomId validation (auto-generated by controller)
roomRoute.post("/create", createRoom);
// Get room needs to validate the roomId from URL params
roomRoute.get("/:roomId", validateRequestBody({ roomId: true }), getRoom);
// Leave room needs to validate the roomId from URL params
roomRoute.post("/leave/:roomId", authMiddleware, validateRequestBody({ roomId: true }), leaveRoom);

export default roomRoute;